<?php

add_action('tgmpa_register', function () {
    $plugins = [
        [
            'name' => 'Advanced Custom Fields PRO',
            'slug' => 'advanced-custom-fields-pro',
//            'source' => get_template_directory().'/plugins/advanced-custom-fields-pro.zip',
            'source' => 'https://drive.google.com/uc?export=download&id=1IezoC6bNRszYfmLRqDd5sKTGEiSKqTHR',
            'required' => true,
            'version' => '6.0.4',
            'force_activation' => true,
            'force_deactivation' => false,
            'external_url' => 'https://www.advancedcustomfields.com/',
        ],
        [
            'name' => 'Advanced Custom Fields: Extended',
            'slug' => 'acf-extended',
            'required' => true,
            'version' => '0.8.8.10',
            'force_activation' => true,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/acf-extended/',
        ],
        [
            'name' => 'EWWW Image Optimizer',
            'slug' => 'ewww-image-optimizer',
            'required' => true,
            'version' => '6.9.2',
            'force_activation' => true,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/ewww-image-optimizer/',
        ],
        [
            'name' => 'WP Rocket',
            'slug' => 'wp-rocket',
//            'source' => get_template_directory().'/plugins/wp-rocket_3.10.8.zip',
            'source' => 'https://drive.google.com/uc?export=download&id=1pIvQFKjoWKlwHxG84C3yEnPh-lQfPyMR',
            'required' => false,
            'version' => '3.10.8',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://wp-rocket.me/',
        ],
        [
            'name' => 'Yoast SEO',
            'slug' => 'wordpress-seo',
            'required' => false,
            'version' => '19.10',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/wordpress-seo/',
        ],
        [
            'name' => 'Yoast Duplicate Post',
            'slug' => 'duplicate-post',
            'required' => false,
            'version' => '4.5',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/duplicate-post/',
        ],
        [
            'name' => 'SVG Support',
            'slug' => 'svg-support',
            'required' => false,
            'version' => '2.5.5',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/svg-support/',
        ],
        [
            'name' => 'Simple Custom CSS and JS',
            'slug' => 'custom-css-js',
            'required' => false,
            'version' => '3.44',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/custom-css-js/',
        ],
        [
            'name' => 'CookieYes | GDPR Cookie Consent',
            'slug' => 'cookie-law-info',
            'required' => false,
            'version' => '3.1.1',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/cookie-law-info/',
        ],
        [
            'name' => 'Contact Form 7',
            'slug' => 'contact-form-7',
            'required' => false,
            'version' => '5.6.4',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/contact-form-7/',
        ],
        [
            'name' => 'Redirection',
            'slug' => 'redirection',
            'required' => false,
            'version' => '5.3.5',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/redirection/',
        ],
        [
            'name' => 'Query Monitor',
            'slug' => 'query-monitor',
            'required' => false,
            'version' => '3.10.1',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/query-monitor/',
        ],
        [
            'name' => 'iThemes Security',
            'slug' => 'better-wp-security',
            'required' => false,
            'version' => '8.1.3',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/better-wp-security/',
        ],
        [
            'name' => 'ManageWP Worker',
            'slug' => 'worker',
            'required' => false,
            'version' => '4.9.15',
            'force_activation' => false,
            'force_deactivation' => false,
            'external_url' => 'https://en-gb.wordpress.org/plugins/worker/',
        ],
    ];

    $config = [
        'id' => 'tb',
        'default_path' => '',
        'menu' => 'tgmpa-install-plugins',
        'parent_slug' => 'themes.php',
        'capability' => 'edit_theme_options',
        'has_notices' => true,
        'dismissable' => true,
        'dismiss_msg' => '',
        'is_automatic' => false,
        'message' => '',
    ];

    foundation_tgmpa($plugins, $config);
});
